#!/usr/bin/env bash
# display PID along with the process name of processes


for pid in /proc/[0-9]*; do
    if [ -r "$pid/comm" ]; then
        name=$(<"$pid/comm")
        if [[ "$name" == *bash* ]]; then
            echo "$(basename "$pid") - $name"
        fi
    fi
done
