#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall


# Alternative: send SIGTERM using the 'pkill' command if available (not kill/killall)
pkill -f '[4]-to_infinity_and_beyond'
