#!/usr/bin/env bash
# This script displays "Best School" 10 times 4th iteration = badluck
#+ 8th iteration = goodluck


a=0
while [ $a -lt 10 ]
do
echo "Best School"
if [ "$a" -eq 3 ]; then
echo "bad luck"
elif [ "$a" -eq 7 ]; then
echo "good luck"
fi
a=$((a + 1))
done