#!/usr/bin/env bash


# Script to configure host resolution for localhost and facebook.com

# Ensure the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Add or update localhost to resolve to 127.0.0.2
sed -i '/127.0.0.2[[:space:]]\+localhost/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts

# Add or update facebook.com to resolve to 8.8.8.8
sed -i '/8.8.8.8[[:space:]]\+facebook\.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts


